<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TesteTecnico.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TesteTecnico.Domain\TesteTecnico.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Remote.Linq" Version="7.3.1" />
      <PackageReference Include="Remote.Linq.Text.Json" Version="7.3.0" />
    </ItemGroup>

</Project>
